#ifndef _KEYBOARD_KEYMAPS_H
#define _KEYBOARD_KEYMAPS_H  

#include <keyboard/keycodes.h>

#define STANDARD_QWERTY  { \
    KEYCODE_NONE, KEYCODE_UNDEFINED, KEYCODE_1, KEYCODE_2, KEYCODE_3, KEYCODE_4, KEYCODE_5, KEYCODE_6, KEYCODE_7, KEYCODE_8, KEYCODE_9, KEYCODE_0, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, \
    KEYCODE_UNDEFINED, KEYCODE_Q, KEYCODE_W, KEYCODE_E, KEYCODE_R, KEYCODE_T, KEYCODE_Y, KEYCODE_U, KEYCODE_I, KEYCODE_O, KEYCODE_P, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, \
    KEYCODE_ENTER, KEYCODE_UNDEFINED, KEYCODE_A, KEYCODE_S, KEYCODE_D, KEYCODE_F, KEYCODE_G, KEYCODE_H, KEYCODE_J, KEYCODE_K, KEYCODE_L, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, \
    KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, KEYCODE_Z, KEYCODE_X, KEYCODE_C, KEYCODE_V, KEYCODE_B, KEYCODE_N, KEYCODE_M, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED, KEYCODE_UNDEFINED \
}

#endif