name: Push Docker Image
on:
    push:
      branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ${GITHUB_WORKSPACE} --file docker/Dockerfile --tag jett59/micos-build:dev
    - name: Test It
      run: docker run --rm -t jett59/micos-build:dev
    - name: Authenticate with Docker
      run: docker login --username jett59 --password ${{ secrets.DOCKER_TOKEN }}
    - name: Push Docker Image
      run: docker push jett59/micos-build:dev
