name: Docker Image CI
on:
    - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ${GITHUB_WORKSPACE} --file docker/Dockerfile --tag micos:test
    - name: Test It
      run: docker run --rm -t micos:test make iso
